name: Cluster Control CI

defaults:
  run:
    working-directory: cluster-control

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'cluster-control/**' 
  pull_request:
    branches: [ main ]
    paths:
      - 'cluster-control/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install ".[lint,test]"
      - name: Run ruff
        run: |
          python3 -m ruff check cluster_control
      - name: Run mypy
        run: |
          python3 -m mypy cluster_control
  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install ".[test]"
      - name: Run unit tests
        run: |
          python3 -m pytest tests/unit
